import type { Metadata } from "next";
import { El_Messiri } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"; // <-- 1. استيراد المكتبة

const elMessiri = El_Messiri({
  subsets: ["arabic"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={elMessiri.className}>
        {children}
        <Toaster position="top-center" reverseOrder={false}  />
      </body>
    </html>
  );
}
